@startuml
interface IAdLoader{
    void loadAd();//加载广告
}
abstract class AdLoader{}
IAdLoader<|--AdLoader
AdLoader <|-- BannerAdLoader
AdLoader <|-- DrawAdLoader
AdLoader <|-- RecyclerAdLoader
AdLoader <|-- RewardVideoLoader
AdLoader <|-- SplashAdLoader
IAdLoader <|-- IPlatformLoader
IPlatformLoader<|--BasePlatformLoader
BasePlatformLoader<|--GDTRecyclerAdWrapper
BasePlatformLoader <|--BDRecyclerLoader
BasePlatformLoader <|--BDSplashAdLoader
@enduml